export const siteData = {
  hero: {
    title: "Chủ nghĩa duy vật lịch sử – Từ trang sử đến đời sống số",
    titleEn: "Historical Materialism – From History to Digital Life",
    subtitle:
      "Hiểu bản chất tồn tại xã hội ↔ ý thức xã hội qua các mốc lịch sử Việt Nam và cách giới trẻ định hình tương lai trong thời đại AI.",
    subtitleEn:
      "Understanding the essence of social existence ↔ social consciousness through Vietnamese historical milestones and how youth shape the future in the AI era.",
    ctaPrimary: "Bắt đầu khám phá",
    ctaPrimaryEn: "Start Exploring",
    ctaSecondary: "Tự kiểm tra nhanh",
    ctaSecondaryEn: "Quick Self-Test",
  },
  coSoLyLuan: [
    {
      id: 1,
      title: "Tồn tại xã hội quyết định ý thức xã hội",
      titleEn: "Social Existence Determines Social Consciousness",
      history: "Đổi mới 1986 – thay đổi KT–XH dẫn đến đổi thay tư duy, ý thức.",
      historyEn: "Doi Moi 1986 – economic-social changes led to shifts in thinking and consciousness.",
      youth: "Internet, AI, toàn cầu hóa định hình cách học & lựa chọn nghề nghiệp.",
      youthEn: "Internet, AI, globalization shape learning methods & career choices.",
      reflect: "Điều kiện sống hiện tại đang 'định hình' mình ở điểm nào?",
      reflectEn: "How are current living conditions 'shaping' you?",
      icon: "Layers",
    },
    {
      id: 2,
      title: "Ý thức xã hội có tính độc lập tương đối",
      titleEn: "Social Consciousness Has Relative Independence",
      history: "Điện Biên Phủ 1954 – ý chí dân tộc thắng dù điều kiện vật chất khó khăn.",
      historyEn: "Dien Bien Phu 1954 – national will triumphed despite material hardships.",
      youth: "Giữ tinh thần sống tích cực dù môi trường học tập áp lực.",
      youthEn: "Maintain positive spirit despite pressured learning environment.",
      reflect: "Mình đã từng vượt hoàn cảnh nhờ niềm tin/ý chí chưa?",
      reflectEn: "Have you overcome circumstances through belief/willpower?",
      icon: "Lightbulb",
    },
    {
      id: 3,
      title: "Kế thừa trong ý thức xã hội",
      titleEn: "Inheritance in Social Consciousness",
      history: "Truyền thống chống giặc, đoàn kết được kế thừa qua nhiều thế hệ.",
      historyEn: "Traditions of resistance and unity inherited across generations.",
      youth: "Kế thừa tinh thần tương thân tương ái trong hoạt động tình nguyện.",
      youthEn: "Inherit the spirit of mutual love through volunteer activities.",
      reflect: "Mình đang kế thừa truyền thống nào của gia đình/cộng đồng?",
      reflectEn: "What family/community traditions are you inheriting?",
      icon: "Users",
    },
    {
      id: 4,
      title: "Cấu trúc ý thức xã hội",
      titleEn: "Structure of Social Consciousness",
      history: "Cách mạng Tháng Tám 1945 – kết hợp tâm lý dân tộc và hệ tư tưởng Mác–Lênin.",
      historyEn: "August Revolution 1945 – combined national psychology and Marxist-Leninist ideology.",
      youth: "Sống xanh, nhân văn, giáo dục khai phóng → hình thành giá trị hành vi mới.",
      youthEn: "Green living, humanism, liberal education → form new behavioral values.",
      reflect: "Tâm lý nhóm & tư tưởng mình theo đuổi đang dẫn tới hành động gì?",
      reflectEn: "How do group psychology & your ideology lead to actions?",
      icon: "Network",
    },
    {
      id: 5,
      title: "Quan hệ tác động qua lại",
      titleEn: "Mutual Interaction Relationship",
      history: "Thống nhất 1975 – nhờ điều kiện KT–QS và ý chí toàn dân.",
      historyEn: "Reunification 1975 – thanks to economic-military conditions and national will.",
      youth: "AI là điều kiện sống; ý thức trách nhiệm số định hướng cách dùng.",
      youthEn: "AI is a living condition; digital responsibility consciousness guides usage.",
      reflect: "Công nghệ thay đổi mình; mình thay đổi cách dùng công nghệ thế nào?",
      reflectEn: "Technology changes you; how do you change how you use technology?",
      icon: "RefreshCw",
    },
  ],
  timeline: [
    {
      year: 1945,
      label: "CM Tháng Tám",
      labelEn: "August Revolution",
      note: "Tâm lý dân tộc + hệ tư tưởng",
      noteEn: "National psychology + ideology",
    },
    {
      year: 1954,
      label: "Điện Biên Phủ",
      labelEn: "Dien Bien Phu",
      note: "Ý chí thắng khó khăn vật chất",
      noteEn: "Will overcomes material hardship",
    },
    {
      year: 1975,
      label: "Thống nhất",
      labelEn: "Reunification",
      note: "Hợp lực vật chất & tinh thần",
      noteEn: "Combined material & spiritual force",
    },
    {
      year: 1986,
      label: "Đổi mới",
      labelEn: "Doi Moi",
      note: "Điều kiện KT–XH đổi, tư duy đổi",
      noteEn: "Economic-social conditions change, thinking changes",
    },
    {
      year: 2025,
      label: "Kỷ nguyên AI",
      labelEn: "AI Era",
      note: "Điều kiện số định hình hành vi",
      noteEn: "Digital conditions shape behavior",
    },
  ],
  matrix: [
    {
      phamTru: "Tồn tại XH quyết định ý thức XH",
      phamTruEn: "Social Existence Determines Social Consciousness",
      chienCong: "Đổi mới 1986",
      chienCongEn: "Doi Moi 1986",
      cauHoi: "Điều kiện sống (AI, Internet) quyết định cách học và định hướng nghề nghiệp của bạn ra sao?",
      cauHoiEn: "How do living conditions (AI, Internet) determine your learning and career orientation?",
    },
    {
      phamTru: "Ý thức XH độc lập tương đối",
      phamTruEn: "Relative Independence of Social Consciousness",
      chienCong: "Điện Biên Phủ 1954",
      chienCongEn: "Dien Bien Phu 1954",
      cauHoi: "Bạn đã từng vượt qua hoàn cảnh khó khăn nhờ niềm tin/ý chí chưa?",
      cauHoiEn: "Have you overcome difficult circumstances through belief/willpower?",
    },
    {
      phamTru: "Kế thừa ý thức XH",
      phamTruEn: "Inheritance of Social Consciousness",
      chienCong: "Kháng chiến chống Mỹ",
      chienCongEn: "Anti-American Resistance",
      cauHoi: "Truyền thống nào của gia đình/bạn bè bạn đang tiếp nối?",
      cauHoiEn: "What family/friend traditions are you continuing?",
    },
    {
      phamTru: "Cấu trúc ý thức XH",
      phamTruEn: "Structure of Social Consciousness",
      chienCong: "Cách mạng Tháng Tám 1945",
      chienCongEn: "August Revolution 1945",
      cauHoi: "Bạn có thấy tâm lý + tư tưởng xã hội ảnh hưởng hành vi sinh viên thế nào?",
      cauHoiEn: "How do you see psychology + social ideology affecting student behavior?",
    },
    {
      phamTru: "Quan hệ tác động qua lại",
      phamTruEn: "Mutual Interaction",
      chienCong: "Thống nhất 1975",
      chienCongEn: "Reunification 1975",
      cauHoi: "Công nghệ thay đổi bạn, nhưng bạn có thể thay đổi cách dùng công nghệ không?",
      cauHoiEn: "Technology changes you, but can you change how you use technology?",
    },
  ],
  youthCases: [
    {
      title: "Học & Nghề",
      titleEn: "Learning & Career",
      tip: "Dùng AI tạo đề cương học; tự sản xuất dự án thực hành nhỏ hàng tuần.",
      tipEn: "Use AI to create study outlines; produce small practical projects weekly.",
      icon: "GraduationCap",
    },
    {
      title: "Tinh thần",
      titleEn: "Mental Health",
      tip: "Chia nhỏ mục tiêu; 25–5 kỹ thuật tập trung; vận động 15'/ngày.",
      tipEn: "Break down goals; 25-5 focus technique; exercise 15 min/day.",
      icon: "Heart",
    },
    {
      title: "Cộng đồng",
      titleEn: "Community",
      tip: "1 giờ/tuần cho hoạt động thiện nguyện hoặc mentor bạn cùng lớp.",
      tipEn: "1 hour/week for volunteer activities or mentoring classmates.",
      icon: "HandHeart",
    },
  ],
  faq: [
    {
      q: "Tồn tại XH có quyết định tuyệt đối?",
      qEn: "Does social existence determine absolutely?",
      a: "Không. Ý thức có độc lập tương đối và tác động ngược.",
      aEn: "No. Consciousness has relative independence and reciprocal effects.",
    },
    {
      q: "Vì sao tách tâm lý xã hội & hệ tư tưởng?",
      qEn: "Why separate social psychology & ideology?",
      a: "Để phân tích lớp cảm xúc–thói quen vs lớp lý luận–chuẩn mực.",
      aEn: "To analyze the emotional-habitual layer vs the theoretical-normative layer.",
    },
    {
      q: "Làm sao áp dụng vào đời sống hàng ngày?",
      qEn: "How to apply to daily life?",
      a: "Nhận thức điều kiện sống ảnh hưởng tư duy; chủ động định hướng hành vi tích cực.",
      aEn: "Recognize how living conditions affect thinking; proactively guide positive behavior.",
    },
  ],
  checklist: [
    {
      id: "doom-scroll",
      label: "Giới hạn doom-scrolling 30 phút/ngày",
      labelEn: "Limit doom-scrolling to 30 min/day",
    },
    {
      id: "ai-skill",
      label: "Học 1 kỹ năng AI ứng dụng mới",
      labelEn: "Learn 1 new applied AI skill",
    },
    {
      id: "volunteer",
      label: "Tham gia hoạt động cộng đồng",
      labelEn: "Join community activities",
    },
    {
      id: "reflect",
      label: "Viết nhật ký phản tư 10 phút",
      labelEn: "Write 10-min reflection journal",
    },
  ],
  quiz: [
    {
      question: "Điều gì quyết định ý thức xã hội?",
      questionEn: "What determines social consciousness?",
      options: [
        { text: "Tồn tại xã hội", textEn: "Social existence", correct: true },
        { text: "Ý chí cá nhân", textEn: "Individual will", correct: false },
        { text: "Giáo dục", textEn: "Education", correct: false },
        { text: "Truyền thống", textEn: "Tradition", correct: false },
      ],
      explanation: "Tồn tại xã hội (điều kiện vật chất, kinh tế) quyết định ý thức xã hội.",
      explanationEn: "Social existence (material, economic conditions) determines social consciousness.",
    },
    {
      question: "Ý thức xã hội có thể tác động ngược lại tồn tại xã hội không?",
      questionEn: "Can social consciousness reciprocally affect social existence?",
      options: [
        { text: "Có, nhờ tính độc lập tương đối", textEn: "Yes, due to relative independence", correct: true },
        { text: "Không, hoàn toàn bị động", textEn: "No, completely passive", correct: false },
        { text: "Chỉ trong trường hợp đặc biệt", textEn: "Only in special cases", correct: false },
        { text: "Chỉ ở giai cấp thống trị", textEn: "Only in ruling class", correct: false },
      ],
      explanation: "Ý thức xã hội có tính độc lập tương đối, có thể tác động ngược lại tồn tại xã hội.",
      explanationEn: "Social consciousness has relative independence and can reciprocally affect social existence.",
    },
    {
      question: "Điện Biên Phủ 1954 minh chứng phạm trù nào?",
      questionEn: "What category does Dien Bien Phu 1954 exemplify?",
      options: [
        { text: "Độc lập tương đối của ý thức XH", textEn: "Relative independence of consciousness", correct: true },
        { text: "Tồn tại quyết định ý thức", textEn: "Existence determines consciousness", correct: false },
        { text: "Kế thừa ý thức", textEn: "Inheritance of consciousness", correct: false },
        { text: "Cấu trúc ý thức", textEn: "Structure of consciousness", correct: false },
      ],
      explanation: "Ý chí dân tộc thắng lợi dù điều kiện vật chất khó khăn → độc lập tương đối.",
      explanationEn: "National will triumphed despite material hardships → relative independence.",
    },
    {
      question: "Đổi mới 1986 thể hiện mối quan hệ gì?",
      questionEn: "What relationship does Doi Moi 1986 demonstrate?",
      options: [
        { text: "Tồn tại XH quyết định ý thức XH", textEn: "Social existence determines consciousness", correct: true },
        { text: "Ý thức độc lập hoàn toàn", textEn: "Consciousness is completely independent", correct: false },
        { text: "Chỉ có yếu tố kinh tế", textEn: "Only economic factors", correct: false },
        { text: "Chỉ có yếu tố chính trị", textEn: "Only political factors", correct: false },
      ],
      explanation: "Thay đổi điều kiện kinh tế–xã hội dẫn đến thay đổi tư duy, ý thức.",
      explanationEn: "Changes in economic-social conditions led to changes in thinking and consciousness.",
    },
    {
      question: "AI & Internet ảnh hưởng giới trẻ theo phạm trù nào?",
      questionEn: "How do AI & Internet affect youth according to which category?",
      options: [
        { text: "Tồn tại XH quyết định ý thức XH", textEn: "Social existence determines consciousness", correct: true },
        { text: "Chỉ là công cụ trung lập", textEn: "Just neutral tools", correct: false },
        { text: "Không liên quan triết học", textEn: "Not related to philosophy", correct: false },
        { text: "Chỉ ảnh hưởng giải trí", textEn: "Only affects entertainment", correct: false },
      ],
      explanation: "Điều kiện số (AI, Internet) là tồn tại xã hội mới, định hình ý thức & hành vi.",
      explanationEn: "Digital conditions (AI, Internet) are new social existence, shaping consciousness & behavior.",
    },
  ],
}
